/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import ResultView from "./script/Result/ResultView"
import RankCell from "./script/RankService/RankCell"
import ResultControl from "./script/Result/ResultControl"
import GameView from "./script/GameView"
import GameControl from "./script/GameControl"
import HomeControl from "./script/HomeControl"
import LoadingControl from "./script/Loading/LoadingControl"
import RankView from "./script/RankService/RankView"
import RankPrizeCell from "./script/RankService/RankPrizeCell"
import RankControl from "./script/RankService/RankControl"
import Option from "./script/prefab/Option"
import Word from "./script/prefab/Word"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/Result/ResultView.js",ResultView);
		reg("script/RankService/RankCell.js",RankCell);
		reg("script/Result/ResultControl.js",ResultControl);
		reg("script/GameView.js",GameView);
		reg("script/GameControl.js",GameControl);
		reg("script/HomeControl.js",HomeControl);
		reg("script/Loading/LoadingControl.js",LoadingControl);
		reg("script/RankService/RankView.js",RankView);
		reg("script/RankService/RankPrizeCell.js",RankPrizeCell);
		reg("script/RankService/RankControl.js",RankControl);
		reg("script/prefab/Option.js",Option);
		reg("script/prefab/Word.js",Word);
    }
}
GameConfig.width = 640;
GameConfig.height = 1136;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "scenes/GameResultView.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
